name: Fetch

on:
  workflow_dispatch:
  schedule:
    # 表达式生成 https://crontab.guru/
    - cron: '30 1 * * 6'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v4
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: 安装依赖
      run: pip install -r requirements.txt
    - name: 执行任务
      run: python ./fetch.py
      
    - name: 提交更改
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: GitHub Actions 
        add: '["list*","snippets/"]'
        fetch: false

    - name: 同步仓库
      uses: actions/checkout@v4 
      with:
        repository: rtian002/abc
        token: ${{secrets.ABC_ACCESS_TOKEN}}
        path: abc
    - name: 复制文件
      run: |
        cp list.txt abc/3
        cd abc && git status
    - name: 同步推送
      uses: EndBug/add-and-commit@v9
      with:
        author_name: rtian002
        author_email: rtian002@gmail.com
        message: "From: AutoMergePublicNodes"
        add: '3 --force'
        cwd: "./abc/"
        fetch: false

